// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/game.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGameRequest struct {
	MaxPlayers           int32    `protobuf:"varint,1,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8434b64ca1d7c55f, []int{0}
}

func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (m *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(m, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetMaxPlayers() int32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

type CreateGameResponse struct {
	GameId               string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameResponse) Reset()         { *m = CreateGameResponse{} }
func (m *CreateGameResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGameResponse) ProtoMessage()    {}
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8434b64ca1d7c55f, []int{1}
}

func (m *CreateGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameResponse.Unmarshal(m, b)
}
func (m *CreateGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameResponse.Marshal(b, m, deterministic)
}
func (m *CreateGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameResponse.Merge(m, src)
}
func (m *CreateGameResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGameResponse.Size(m)
}
func (m *CreateGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameResponse proto.InternalMessageInfo

func (m *CreateGameResponse) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type JoinGameRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGameRequest) Reset()         { *m = JoinGameRequest{} }
func (m *JoinGameRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGameRequest) ProtoMessage()    {}
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8434b64ca1d7c55f, []int{2}
}

func (m *JoinGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameRequest.Unmarshal(m, b)
}
func (m *JoinGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameRequest.Marshal(b, m, deterministic)
}
func (m *JoinGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameRequest.Merge(m, src)
}
func (m *JoinGameRequest) XXX_Size() int {
	return xxx_messageInfo_JoinGameRequest.Size(m)
}
func (m *JoinGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameRequest proto.InternalMessageInfo

func (m *JoinGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type JoinGameResponse struct {
	AssignedPlayerId     string   `protobuf:"bytes,1,opt,name=assigned_player_id,json=assignedPlayerId,proto3" json:"assigned_player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGameResponse) Reset()         { *m = JoinGameResponse{} }
func (m *JoinGameResponse) String() string { return proto.CompactTextString(m) }
func (*JoinGameResponse) ProtoMessage()    {}
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8434b64ca1d7c55f, []int{3}
}

func (m *JoinGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameResponse.Unmarshal(m, b)
}
func (m *JoinGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameResponse.Marshal(b, m, deterministic)
}
func (m *JoinGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameResponse.Merge(m, src)
}
func (m *JoinGameResponse) XXX_Size() int {
	return xxx_messageInfo_JoinGameResponse.Size(m)
}
func (m *JoinGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameResponse proto.InternalMessageInfo

func (m *JoinGameResponse) GetAssignedPlayerId() string {
	if m != nil {
		return m.AssignedPlayerId
	}
	return ""
}

type StartGameRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8434b64ca1d7c55f, []int{4}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateGameRequest)(nil), "proto.CreateGameRequest")
	proto.RegisterType((*CreateGameResponse)(nil), "proto.CreateGameResponse")
	proto.RegisterType((*JoinGameRequest)(nil), "proto.JoinGameRequest")
	proto.RegisterType((*JoinGameResponse)(nil), "proto.JoinGameResponse")
	proto.RegisterType((*StartGameRequest)(nil), "proto.StartGameRequest")
}

func init() { proto.RegisterFile("server/proto/game.proto", fileDescriptor_8434b64ca1d7c55f) }

var fileDescriptor_8434b64ca1d7c55f = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x09, 0xd8, 0x6a, 0xe7, 0x62, 0x9c, 0x43, 0x53, 0x23, 0x88, 0xe4, 0x24, 0x7e, 0x6c,
	0xc0, 0x1e, 0xf5, 0xa0, 0x88, 0x48, 0x3d, 0x49, 0x7c, 0x80, 0xb2, 0x25, 0x63, 0x08, 0x34, 0xd9,
	0xb8, 0xbb, 0x15, 0xfb, 0x7e, 0x3e, 0x98, 0x64, 0x3f, 0x4c, 0x68, 0x15, 0x7a, 0x4a, 0x66, 0xe6,
	0xf7, 0xdf, 0xf9, 0xcf, 0x0c, 0x44, 0x8a, 0xe4, 0x27, 0xc9, 0xb4, 0x91, 0x42, 0x8b, 0xb4, 0xe0,
	0x15, 0x31, 0xf3, 0x8b, 0x03, 0xf3, 0x89, 0x4f, 0x0a, 0x21, 0x8a, 0x25, 0xd9, 0xfa, 0x62, 0xf5,
	0x9e, 0x52, 0xd5, 0xe8, 0xb5, 0x65, 0x92, 0x29, 0x1c, 0x3d, 0x4a, 0xe2, 0x9a, 0x9e, 0x79, 0x45,
	0x19, 0x7d, 0xac, 0x48, 0x69, 0x3c, 0x05, 0xa8, 0xf8, 0xd7, 0xeb, 0x92, 0xaf, 0x49, 0xaa, 0x49,
	0x70, 0x16, 0x9c, 0x0f, 0xb2, 0x5e, 0x26, 0xb9, 0x06, 0xec, 0x8b, 0x54, 0x23, 0x6a, 0x45, 0x18,
	0xc1, 0x7e, 0xdb, 0x7c, 0x5e, 0xe6, 0x46, 0x32, 0xca, 0x86, 0x6d, 0x38, 0xcb, 0x93, 0x0b, 0x38,
	0x7c, 0x11, 0x65, 0xdd, 0xef, 0xf0, 0x2f, 0x7b, 0x0f, 0x61, 0xc7, 0xba, 0x87, 0xaf, 0x00, 0xb9,
	0x52, 0x65, 0x51, 0x53, 0x3e, 0x6f, 0x8c, 0x85, 0x4e, 0x17, 0xfa, 0x8a, 0xf5, 0x36, 0xcb, 0x93,
	0x4b, 0x08, 0xdf, 0x34, 0x97, 0x7a, 0x97, 0x76, 0x37, 0xdf, 0x01, 0xec, 0xb5, 0x20, 0x3e, 0x00,
	0x74, 0x23, 0xe1, 0xc4, 0x6e, 0x87, 0x6d, 0xad, 0x26, 0x3e, 0xfe, 0xa3, 0xe2, 0x6c, 0xde, 0xc2,
	0x81, 0xb7, 0x8e, 0x63, 0x87, 0x6d, 0xcc, 0x1d, 0x47, 0x5b, 0x79, 0x27, 0xbe, 0x83, 0xd1, 0xaf,
	0x6b, 0xf4, 0xd4, 0xe6, 0x1c, 0xf1, 0x98, 0xd9, 0x5b, 0x32, 0x7f, 0x4b, 0xf6, 0xd4, 0xde, 0x72,
	0x31, 0x34, 0xf1, 0xf4, 0x27, 0x00, 0x00, 0xff, 0xff, 0xed, 0x3e, 0x04, 0x93, 0x0b, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error) {
	out := new(JoinGameResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/JoinGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Game/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error)
	StartGame(context.Context, *StartGameRequest) (*empty.Empty, error)
}

// UnimplementedGameServer can be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (*UnimplementedGameServer) CreateGame(ctx context.Context, req *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (*UnimplementedGameServer) JoinGame(ctx context.Context, req *JoinGameRequest) (*JoinGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (*UnimplementedGameServer) StartGame(ctx context.Context, req *StartGameRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/JoinGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).JoinGame(ctx, req.(*JoinGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _Game_CreateGame_Handler,
		},
		{
			MethodName: "JoinGame",
			Handler:    _Game_JoinGame_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _Game_StartGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/game.proto",
}
